# -------------------------
# Streamlit Secrets
# -------------------------

SHEET_ID = "1YxYzF_L4rPD4tWrHb_j2HstZdXXj1-6pXBMB1X_M1u4"

GOOGLE_CREDENTIALS = '''
{
  "type": "service_account",
  "project_id": "harlem-wizards-app",
  "private_key_id": "78a17a42551980d9ee81372b38274f5e24a2fd56",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCht05BDRe6Xyi6\niCXHxFozxjpqrS9rp+YcrigS/Bpnrgu6Q2EwcQYwhMs5hj9IM5R+AVcaB88Q3SuB\nthtwFdxL6z9BQ7k1NDI+QycS97CRoaR8HqyiBQvfvl1cpUlkw2uAPD7WW8qYjKdg\n6C+v3GgsSx/ANu2xUdpm3Y6Vx+612DB85GcmhAsALZ296BYCfrXIKaxxaGxJPgoD\nqrRejR7p1rvrrZ0BRV7NQiJrg/7jpySJPoIlvjlpjxkfAhZpR7k5DL6BO/LCMhzx\nj8O9K2abqVwaAWe89Ejqyq+oWUSasIWdGzc2WHgz6tUD3AYLvM+ZK4H4V2Z8mEOG\nwnYUfdf5AgMBAAECggEAAd+DTRJQ13898PspofRaRO7jZfcZvsiREfFtX/IxC2CR\nnMBU3GY7d5NPRpCRgUHcDS03KT16pFSiwUeAV0/VJTVshwxzCaNEls3ZaGB4ni57\nHuK8zA/8uCFzywVIirT4BlaVB2Eh5CZyvAtXV+DYw1HZQZJVqniq93uBHUns0s66\nEL16vKnyFEC78wOjhWpqR4BSIJbx5Zw3PznLuBJICF0J3zTRpaagGvN5+NbtNLGJ\n2+7YWcDFiMQqySwmpUbRBKWfKuVW5syFMo/18S5TsZXyAt9oCNajLtys3ctv8b2s\nGoEQhf5hyCDDQx+n0bqwf3offO0i3P0zlQCngStuyQKBgQDToq+Gv/DA//4Nne46\n0iVQeJFbBffihOt6XChTMS676eM7r0ZEAyxduOA02C5HzaDG/ndlLBHpTRS5QIAe\nkGHniry/nhsRHoNPe/GkbVh1wCfsIDLOZHyjtarNLk1ZGWSQb9sE/dKYDKnXdlu8\naRDFxtBac7o2hMwPrZOCk2sBHwKBgQDDnbeY+pxMJCZrewxwUzLuE6tj7+Qz26V6\nz5DWpQ9f9jVWdSJyGM0s8RUIBPWdlWAR/k62fwceejXZn3bO9SmZFPy6WAMmRKbk\n0vs3RRBkeFrCasQdR4BIqhrDqNoYe4of6rIFxteA4MzwOU8461hyjpMt+Gp80VRw\n6bh/vCyL5wKBgQCG3P4jzX67TqZzwPeGDlJvBFYEfjon5HI2qDGeShIw92uxphEN\n2EPWebCOnFBpu1TAWnp1Q28qj88r+jlqwLFTHqsHJNa0wxAEf8RN9sxPRSNrql0V\n/x0aKfNtCxuJMtBN5qnYdXNVJ4S35BmzZ/SjQ/2UFnlMsrVjLEZ7CDxBGwKBgBdo\n8YbiPwAxt1NXh3aNzmOFgRZVqCa4m4Yl/vxhBoUCbwGoxPWImE1PkKfECCzSqouc\ntojKjOyNzZH8rng4CMFkLJaUX9QdlSd/REcqAbs0WBA6PLwQSX7otIlD1M3nQvFs\n4d8lG7c1r/DzutJh/9S90UlIGF5VothccBMBTwdzAoGAJmeXI1iC7S//Pkg5jZiu\nm9f/auD3Blui1EPoOtm+ba9hVBIq37w/hL1gtYgiNaAS2EXeU+HL9a1oLdVquPZW\nCneTkJ5nxamwkqkKwLtmgaar64nOeCrV8HbN51Bn/AQKueWbe2zmdd6HaGYGGxa3\neXSRTbkpIhP734NmMltJASI=\n-----END PRIVATE KEY-----\n",
  "client_email": "streamlit-sheets@harlem-wizards-app.iam.gserviceaccount.com",
  "client_id": "107621464293564761069",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-sheets%40harlem-wizards-app.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
'''
